version: '3.8'

services:
  denode-app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'inventory'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  appnet:
    driver: bridge
